#!/bin/sh

set -e
# Use exapmples
# rtc-test second_since_epoch write #This will set system and hwclock date [date "+%s"]
# rtc-test second_since_epoch #This will return 0 if rtc time was preserved after powercycle 1 otherwise;
#
#https://docs.amd.com/r/en-US/ug1087-zynq-ultrascale-registers/CALIB_WRITE-RTC-Register
#Read CALIB_READ(RTC) register: sudo devmem 0x00ffa6000c 32
#Wrie CALIB_WRITE(RTC) register: sudo devmem 0x00ffa60008 32 0x7fff
#
#

aprox=20
ref=$1
if [ "$2" ]; then
	date -s '@'$1
	#reset calibration
	devmem 0x00ffa60008 32 0x7fff
	#rtc set time
	hwclock -w;
else

	hwclk=$(devmem 0x00ffa60010 32)
	calib=$(devmem 0x00ffa6000c 32)
	sse=$(($hwclk))
	low=$(($ref - $aprox))
	high=$(($ref + $aprox))
	drift=$(($ref - $sse))
	if (( sse >= low && sse <= high )); then
		echo OK ref:$ref, rtc:$sse, drift:$drift, calib: $caib, low:$low, high:$high;
		exit 0;
	else
		echo FAIL ref:$ref, rtc:$sse, drift:$drift, calib: $caib, low:$low, high:$high;
		exit 1;
	fi

	exit 0;
fi
